export const actionConstant = {
    GET_GIT_USERS_REQUEST: 'GET_GIT_USERS_REQUEST',
    GET_GIT_USERS_SUCCESS: 'GET_GIT_USERS_SUCCESS',
    GET_GIT_USERS_ERROR: 'GET_GIT_USERS_ERROR',

    GET_GIT_PROJECTS_REQUEST: 'GET_GIT_PROJECTS_REQUEST',
    GET_GIT_PROJECTS_SUCCESS: 'GET_GIT_PROJECTS_SUCCESS',
    GET_GIT_PROJECTS_ERROR: 'GET_GIT_PROJECTS_ERROR',

    ADD_GROUP_REQUEST: 'ADD_GROUP_REQUEST',
    ADD_GROUP_SUCCESS: 'ADD_GROUP_SUCCESS',
    ADD_GROUP_ERROR: 'ADD_GROUP_ERROR'
};